//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mathematics.Mathematica {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mathematics.Mathematica.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] Clear {
            get {
                object obj = ResourceManager.GetObject("Clear", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ConfidenceInterval {
            get {
                object obj = ResourceManager.GetObject("ConfidenceInterval", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Portfolio {
            get {
                object obj = ResourceManager.GetObject("Portfolio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PortfolioDiscrete {
            get {
                object obj = ResourceManager.GetObject("PortfolioDiscrete", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PortfolioMargin {
            get {
                object obj = ResourceManager.GetObject("PortfolioMargin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PortfolioMarginBalance {
            get {
                object obj = ResourceManager.GetObject("PortfolioMarginBalance", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
