//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathematicsUnits {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MathematicsUnits.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2011:01:07 - 21:29:36.602 - 3464&gt; MtTick(): [EURUSD] Bid = 1.29111 Ask = 1.29119
        ///2011:01:07 - 21:29:45.472 - 3960&gt; MtTick(): [EURUSD] Bid = 1.29111 Ask = 1.2912
        ///2011:01:07 - 21:30:13.452 - 3868&gt; MtTick(): [EURUSD] Bid = 1.29121 Ask = 1.29138
        ///2011:01:07 - 21:30:14.501 - 4460&gt; MtTick(): [EURUSD] Bid = 1.29127 Ask = 1.29146
        ///2011:01:07 - 21:30:20.309 - 4484&gt; MtTick(): [EURUSD] Bid = 1.29131 Ask = 1.29146
        ///2011:01:07 - 21:30:20.710 - 1412&gt; MtTick(): [EURUSD] Bid = 1.29131 Ask = 1.29148
        ///2011:01:07 - 21:30:21 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ticks {
            get {
                return ResourceManager.GetString("Ticks", resourceCulture);
            }
        }
    }
}
